### ISSUE TITLE
Great job! Some questions

### ISSUE THREAD

**Issue by Polisvh** [Mixces/Legacy-Animations#1]
My dear friend I see u doing really great job out here, but I have couple questions

- will you add a swordblock mechanics that do not require a shield in your off hand (purely visual) because the sword block animation seems to not work at the moment without a shield in offhand
- will you add support to further versions like 1.21?

To precise my first question, I am asking about sword block mechanics that work the same as on labymod
- you can still deal damage and take damage
- you can still run
- it's pure visual - does not affect the gameplay at all

**Comment by Mixces** [comment]
Hey, thanks for reaching out to me!

> * will you add a swordblock mechanics that do not require a shield in your off hand (purely visual) because the sword block animation seems to not work at the moment without a shield in offhand

I most likely won't allow the sword to be (visually) block-able outside of shield blocking, and if I do, it probably won't be done until I finalize some of my other features. Sorry 😭. 

> * will you add support to further versions like 1.21?

Yes! I am in the process of updating it as of right now actually! Beta 2 will be for 1.21! 👍

> To precise my first question, I am asking about sword block mechanics that work the same as on labymod
> 
> * you can still deal damage and take damage
> * you can still run
> * it's pure visual - does not affect the gameplay at all

I see I see. Yeah, I don't foresee myself add this anytime soon, but, if I do, I'll let you know! 🥶
