### ISSUE TITLE
suggestions PLZ READ

### ISSUE THREAD

**Issue by RealSoy** [Mixces/Legacy-Animations#2]
1. make a setting that disables head interpolation (in the latest versions the player head turning is smoothed out which looks weird imo)
2. 1.21 support!

**Comment by Polisvh** [comment]
Oh yeah head interpolation would be really cool as well

**Comment by Mixces** [comment]
Thanks for reaching out to me!

> 1. make a setting that disables head interpolation (in the latest versions the player head turning is smoothed out which looks weird imo)

This feature is actually already done, and it will be available in the next beta release! 👍

> 2. 1.21 support!

Coming soon! 💪

**Comment by RealSoy** [comment]
thanks bro this the best 1.7 animations mod ive used
