### ISSUE TITLE
archive

### ISSUE THREAD

**Issue by RealSoy** [Mixces/Legacy-Animations#4]
Hi, i saw this was archived a while ago but now its back, is this still being worked on? I neeeed the mod that disables smooth head rotations 😊

**Comment by Mixces** [comment]
> Hi, i saw this was archived a while ago but now its back, is this still being worked on? I neeeed the mod that disables smooth head rotations 😊

Yes! This mod is being worked on, but, I'm re-writing it from scratch and moving it to another repo right now! I'll let you know when I make it public.

**Comment by RealSoy** [comment]
yay glad to hear that

**Comment by Mixces** [comment]
> yay glad to hear that

I will make the new repo public for you to build the mod soon 👍🏾 I specifically added the "disable smooth head rotation" feature you wanted 😂

**Comment by RealSoy** [comment]
thank u so much, when do u think the repo will be public?

**Comment by Mixces** [comment]
> thank u so much, when do u think the repo will be public?

It's public now! Thanks for reminding me 🤣 

Feel free to open an issue on the new repo or message me on discord if you need anything!

https://github.com/Mixces/Animatium/releases/tag/1.0.0
